- name: Setup macos
  hosts: localhost
  tasks:
    - name: Set facts
      ansible.builtin.set_fact:
        cacheable: true
        is_mac: ansible_facts['os_family'] == "Darwin"

    - name: Install brew packages
      ansible.builtin.import_tasks:
        file: tasks/brew-packages.yaml
      when: is_mac

    - name: Link config
      ansible.builtin.import_tasks:
        file: tasks/config.yaml
