- name: Install volta
  community.general.homebrew:
    name: volta
  when: ("volta" not in installed_brew_formulae)

- name: Link .npmrc
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/files/ecmascript/.npmrc"
    dest: ~/.npmrc
    state: link

- name: Gather installed volta tools
  ansible.builtin.command:
    cmd: volta list --format plain
  register: installed_volta_tools
  changed_when: false

- name: Install global tools
  ansible.builtin.command:
    cmd: "volta install {{ item }}"
  when: item not in installed_volta_tools.stdout
  changed_when: item not in installed_volta_tools.stdout
  loop:
    - node
    - pnpm
