- name: Generate .gitconfig
  ansible.builtin.template:
    src: "{{ ansible_env.PWD }}/files/git/.gitconfig.j2"
    dest: ~/.gitconfig
    mode: "0755"

- name: Persistent git user info for work
  ansible.builtin.template:
    src: "{{ ansible_env.PWD }}/files/git/.gitconfig_work.j2"
    dest: ~/.gitconfig_work
    mode: "0755"

- name: Install git tools
  community.general.homebrew:
    name: "{{ item }}"
  when: item not in installed_brew_formulae
  loop:
    - gh
