- name: Link .gitconfig
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/files/git/.gitconfig"
    dest: ~/.gitconfig
    state: link

- name: Persistent git user info for work
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/files/git/.gitconfig_work"
    dest: ~/.gitconfig_work
    state: link

- name: Install git tools
  community.general.homebrew:
    name: "{{ item }}"
  when: item not in installed_brew_formulae
  loop:
    - gh
