- name: Install hammerspoon
  community.general.homebrew_cask:
    name: "{{ item }}"
  when: item not in installed_brew_casks
  loop:
    - hammerspoon

- name: Link hammerspoon config
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/files/hammerspoon"
    dest: ~/.hammerspoon
    state: link
