- name: Install nerd fonts
  community.general.homebrew_cask:
    name: "homebrew/cask-fonts/{{ item }}"
  when: item not in installed_brew_casks
  loop:
    - font-fira-code-nerd-font
    - font-hack-nerd-font

- name: Install modern cli tools
  community.general.homebrew:
    name: "{{ item }}"
  when: item not in installed_brew_formulae
  loop:
    - fd
    - ripgrep

- name: Install ui apps
  community.general.homebrew_cask:
    name: "{{ item }}"
  when: item not in installed_brew_casks
  loop:
    - microsoft-edge
    - raycast
    - snipaste
    - visual-studio-code

- name: Add quicklook extensions
  community.general.homebrew_cask:
    name: "{{ item }}"
  when: item not in installed_brew_casks
  loop:
    - qlimagesize
    - qlmarkdown
    - qlvideo
    - quicklook-json
