- name: Ensure ~/.config exists
  ansible.builtin.file:
    path: ~/.config
    state: directory
    mode: "0755"

- name: List installed homebrew formulae
  ansible.builtin.command:
    cmd: brew list --formula
  register: brew_formula_list_output
  changed_when: false

- name: List installed homebrew casks
  ansible.builtin.command:
    cmd: brew list --cask
  register: brew_cask_list_output
  changed_when: false

- name: Fetch url at work
  ansible.builtin.uri:
    url: http://rnpm.hz.netease.com
    status_code:
      - 200
      - 403
  register: workspace_net_access

- name: Set facts
  ansible.builtin.set_fact:
    cacheable: true
    with_workspace_net: "{{ workspace_net_access.status == 200 }}"
    installed_brew_formulae: "{{ brew_formula_list_output.stdout_lines }}"
    installed_brew_casks: "{{ brew_cask_list_output.stdout_lines }}"
    work_name: "{{ lookup('file', 'secrets/work_name') }}"
    work_email: "{{ lookup('file', 'secrets/work_email') }}"
    work_npm_registry: "{{ lookup('file', 'secrets/work_npm_registry') }}"
    personal_name: "{{ lookup('file', 'secrets/personal_name') }}"
    personal_email: "{{ lookup('file', 'secrets/personal_email') }}"
