- name: Link .zshrc
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/files/shell/.zshrc"
    dest: ~/.zshrc
    state: link

- name: Install zsh plugins
  community.general.homebrew:
    name: "{{ item }}"
  when: item not in installed_brew_formulae
  loop:
    - autojump
    - zsh-syntax-highlighting
    - zsh-autosuggestions
