- name: Install terminals
  community.general.homebrew_cask:
    name: "{{ item }}"
  when: item not in installed_brew_casks
  loop:
    - wezterm

- name: Link wezterm config
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/files/wezterm"
    dest: ~/.config/wezterm
    state: link

- name: Install modern cli tools
  community.general.homebrew:
    name: "{{ item }}"
  when: item not in installed_brew_formulae
  loop:
    - fd
    - ripgrep
    - joshuto

- name: Link .zshrc
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/files/shell/.zshrc"
    dest: ~/.zshrc
    state: link

- name: Install zsh plugins
  community.general.homebrew:
    name: "{{ item }}"
  when: item not in installed_brew_formulae
  loop:
    - autojump
    - zsh-syntax-highlighting
    - zsh-autosuggestions
