- name: Install volta
  community.general.homebrew:
    name: volta
  when: ("volta" not in installed_brew_formulae.stdout_lines)

- name: Link .npmrc
  ansible.builtin.file:
    src: '{{ ansible_env.PWD }}/roles/lang/files/.npmrc'
    dest: ~/.npmrc
    state: link

- name: Gather installed volta tools
  ansible.builtin.command:
    cmd: volta list --format plain
  register: installed_volta_tools
  changed_when: false

- name: Install global tools
  ansible.builtin.command:
    cmd: "volta install {{ item }}"
  ignore_errors: true
  when: (item not in installed_volta_tools.stdout)
  loop:
    - node
    - pnpm
    - "@cloudmusic-desktop/cli"
