return {
  Diagnostic = {
    Error = "",
    Warn = "",
    Info = "󰋼",
    Hint = "󰌵",
  },
  LspKind = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Constant = " ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = " ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = " ",
    Module = " ",
    Namespace = " ",
    Null = " ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
    Collapsed = "",
  },
  Heirline = {
    ArrowLeft = "",
    ArrowRight = "",
    BufferClose = "󰅖",
    FileModified = "",
    FileReadOnly = "",
    FoldClosed = "",
    FoldOpened = "",
    GitAdd = "",
    GitBranch = "",
    GitChange = "",
    GitDelete = "",
    MacroRecording = "",
    sep = "",
  },
  WhichKeyPrefix = {
    ActiveLSP = "",
    Package = "󰏖",
    Search = "",
    Tab = "󰓩",
    Window = "",
    Git = "󰊢",
    Neorg = "",
  },
  UI = {
    Selected = "❯",
  },
}
