- name: Create ~/.config
  ansible.builtin.file:
    path: ~/.config
    state: directory
    mode: '0755'

- name: Gather installed homebrew formulae
  ansible.builtin.command:
    cmd: brew list --formula
  register: installed_brew_formulae
  changed_when: false

- name: Gather installed homebrew casks
  ansible.builtin.command:
    cmd: brew list --cask
  register: installed_brew_casks
  changed_when: false
